URL_SERVICE = "https://cebcee6e-4235-454c-956d-dc44f2a6c6d5.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
CREATE_USER_PATH = "/api/v1/users/"
